services:
  api1: &api # image: Dockerfile # TODO set image here
    build:
      context: .
      dockerfile: ./Dockerfile
    hostname: api1
    environment:
      - REDIS_URL=redis://redis:6379
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - RUST_LOG=info
    networks:
      - backend
      - payment-processor
    ports:
      - :9999
    depends_on:
      - redis
      - nginx
    deploy:
      resources:
        limits:
          cpus: "0.380"
          memory: "80MB"

  api2:
    <<: *api
    hostname: api2

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 9999:9999
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 50M

  redis:
    image: redis:7.2-alpine
    container_name: redis
    command: redis-server --save "" --appendonly no --maxclients 20000
    networks:
      - backend
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "50MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
