services:
  api:
    # image: Dockerfile # TODO set image here
    build:
      context: .
      dockerfile: ./Dockerfile
    hostname: api
    environment:
      - REDIS_URL=redis://localhost:6379
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    networks:
      - backend
      - payment-processor
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "9999:9999"
    deploy:
      # resources:
      #   limits:
      #     cpus: "0.55"
      #     memory: "30MB"

  redis:
    image: redis:7.2-alpine
    container_name: redis
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "275MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
