# https://taskfile.dev

version: "3"

tasks:
  default:
    - task: up

  all:
    - task: fmt
    - task: clippy

  build:
    cmds:
      - cargo build
      - clear
      - task: serve

  release:
    cmds:
      - cargo build --release

  check:
    - task: fmt
    - task: clippy

  fmt:
    cmds:
      - taplo fmt
      - cargo fmt

  clippy:
    cmds:
      - cargo clippy

  serve:
    env:
      REDIS_URL: "redis://127.0.0.1:6379"
      PROCESSOR_DEFAULT_URL: "http://payment-processor-default:8080"
      PROCESSOR_FALLBACK_URL: "http://payment-processor-fallback:8080"
    cmds:
      - ./target/debug/backend

  reset-redis:
    cmds:
      - docker compose -f ./docker-compose.yml up -d redis
      - redis-cli DEL fallback_set
      - redis-cli DEL default_set
      - docker compose -f ./docker-compose.yml down

  k6:
    # env:
      # K6_WEB_DASHBOARD: true
      # K6_WEB_DASHBOARD_PORT: 5665
      # K6_WEB_DASHBOARD_PERIOD: 2s
      # K6_WEB_DASHBOARD_OPEN: true
      # K6_WEB_DASHBOARD_EXPORT: "report.html"
    dir: rinha-test
    cmds:
      - k6 run rinha.js

  up:
    env:
      COMPOSE_BAKE: true
    cmds:
      - clear
      - docker compose -f payment-processor/docker-compose-arm64.yml up --detach
      - docker compose up --build api1 --build api2 --detach 

  down:
    cmds:
      - clear
      - docker compose -f payment-processor/docker-compose-arm64.yml down
      - docker compose -f ./docker-compose.yml down
