# https://taskfile.dev

version: "3"

tasks:
  default:
    deps: [build]

  all:
    - task: fmt
    - task: clippy

  build:
    cmds:
      - cargo build

  release:
    cmds:
      - cargo build --release

  fmt:
    cmds:
      - cargo fmt

  clippy:
    cmds:
      - cargo clippy
