# https://taskfile.dev

version: "3"

tasks:
  default:
    - task: backend-up

  all:
    - task: fmt
    - task: clippy

  build:
    cmds:
      - cargo build
      - clear
      - task: serve

  release:
    cmds:
      - cargo build --release

  check:
    - task: fmt
    - task: clippy

  fmt:
    cmds:
      - taplo fmt
      - cargo fmt

  clippy:
    cmds:
      - cargo clippy

  serve:
    cmds:
      - ./target/debug/backend

  backend-up:
    env:
      COMPOSE_BAKE: true
    cmds:
      - clear
      - docker compose -f payment-processor/docker-compose-arm64.yml up --detach
      - docker compose -f ./docker-compose.yml up --build api

  backend-down:
    cmds:
      - clear
      - docker compose -f payment-processor/docker-compose-arm64.yml down
      - docker compose -f ./docker-compose.yml down
