# https://taskfile.dev

version: "3"

tasks:
  default:
    - task: backend-up

  all:
    - task: fmt
    - task: clippy

  build:
    cmds:
      - cargo build
      - clear
      - task: serve

  release:
    cmds:
      - cargo build --release

  check:
    - task: fmt
    - task: clippy

  fmt:
    cmds:
      - taplo fmt
      - cargo fmt

  clippy:
    cmds:
      - cargo clippy

  serve:
    cmds:
      - ./target/debug/backend

  backend-up:
    cmds:
      - docker compose --project-directory . -f payment-processor/docker-compose-arm64.yml -f ./docker-compose.yml up
