# https://taskfile.dev

version: "3"

tasks:
  default:
    - task: build
    - clear
    - task: serve

  all:
    - task: fmt
    - task: clippy

  build:
    cmds:
      - cargo build

  release:
    cmds:
      - cargo build --release

  check:
    - task: fmt
    - task: clippy

  fmt:
    cmds:
      - taplo fmt
      - cargo fmt

  clippy:
    cmds:
      - cargo clippy

  serve:
    cmds:
      - ./target/debug/backend
